### ISSUE TITLE
Use original GriefPrevention plugin as dependency

### ISSUE THREAD

**Issue by DmitryRendov** [EtienneDx/RealEstate#14]
I understand a reason for this solution and I'm using own customized version of GP as well. It's tricky to merge all them together)

Hope you will find a way to merge your API into the original GriefPrevention soon.

**Comment by EtienneDx** [comment]
In discussion with RoboMWM right now, hopefully he will merge it soon :)

**Comment by antcro74** [comment]
I'd like to use the original GriefPrevention as well, did you get any update ?

In case I use the original would it still partially work ? I don't mind removing de permission for loans if that's the issue.

Thanks for your time.

**Comment by EtienneDx** [comment]
I'm afraid they're aren't compatible...
I might re-update the modified version, but I'm kinda busy rn...
For the best, I'll need GP to finish working on it's latest version but I think that's still way off, sorry :/

**Comment by joex92** [comment]
Damn... I hope you update it soon...
one of the servers were I'm staff wants to update to 1.16.4 but it seems like the latest release doesn't work on 1.16.4...

**Comment by joex92** [comment]
I just tried the plugin on 1.16.4 and it still works... still, try to find some time to update it... merry christmas! :)

**Comment by joex92** [comment]
> I'm afraid they're aren't compatible...
> I might re-update the modified version, but I'm kinda busy rn...
> For the best, I'll need GP to finish working on it's latest version but I think that's still way off, sorry :/

Hey, I was thinking... 
if in the end you can't make it possible for the RE plugin to use the original GP, then why not just merging both, modified GP and RE, into 1 plugin? that way it could be like an alternative to the original GP + RE features... also because it's sometimes is annoying downloading 2 files and also the name of the modified GP is the same as the original GP... I believe this would be better...  well, it's just a suggestion...

I hope you keep updating the plugin when 1.18 comes out...

**Comment by EtienneDx** [comment]
Hey, that's a great suggestion! You probably guessed it, I've had very little time, and I'm afraid I still won't have for a while... I'll keep you posted, and will try to keep updating whenever I can. Thanks a lot for using the plugin even with the lack of updates though !

**Comment by joex92** [comment]
Well I imagined you would have been busy because of **life**...
Anyways, if a "merging" comes, then you could add a way to create 3D subdivisions, adding a `/subdivide3dclaims`-like command... idk... I believe merging everything into 1 GP alternative plugin could give you a wider scope to add features GP might not have... I´ll be waiting for it... so keep it up! 👍

**Comment by EtienneDx** [comment]
Haha, that's getting next level but it could be great :)

**Comment by EtienneDx** [comment]
All things considered, I will include the modified GP into the next RE release, to clear this confusion, but will not include any direct modifications to GP within it. If you have specific suggestions for new GP features that won't be developped by the GP devs, you can always post issues [here](https://github.com/EtienneDx/GriefPrevention/issues), and I'll look into them at some point. Doing so would definitely split RE and GP though, so I'm not sure of anything for now :)

**Comment by joex92** [comment]
ok cool... but why would adding new features split RE from modified GP?

**Comment by joex92** [comment]
> All things considered, I will include the modified GP into the next RE release, to clear this confusion, but will not include any direct modifications to GP within it. If you have specific suggestions for new GP features that won't be developped by the GP devs, you can always post issues [here](https://github.com/EtienneDx/GriefPrevention/issues), and I'll look into them at some point. Doing so would definitely split RE and GP though, so I'm not sure of anything for now :)
> 
> The new jar will be available from #36

created the issue at EtienneDx/GriefPrevention#3 and also at TechFortress/GriefPrevention#1570 just in case...

**Comment by EtienneDx** [comment]
It would split the modified GP with the original, and RE depends on the modified version...
It wouldn't be 100% incompatible but some updates may start taking much longer :/

**Comment by joex92** [comment]
> It would split the modified GP with the original, and RE depends on the modified version...
> It wouldn't be 100% incompatible but some updates may start taking much longer :/

Then just go with the merge update for now... 

> It would split the modified GP with the original, and RE depends on the modified version...
> It wouldn't be 100% incompatible but some updates may start taking much longer :/

Then go with the merge update for now and let's see if they decide to add it, because it seems like it wasn't rejected at all, here TechFortress/GriefPrevention#269

**Comment by Jikoo** [comment]
Would like to point out that at this point there's support for everything in base GP to not need your own fork for RealEstate's functionality. Granted, there isn't yet an official release, but with TechFortress/GriefPrevention#1006 the API is sufficient.

The `ClaimPermissionCheckEvent` covers all your trust needs. This replaces `IAddonPlugin#allowAccess`, `IAddonPlugin#allowBuild`, `IAddonPlugin#allowEdit`, `IAddonPlugin#allowContainers`, and `IAddonPlugin#allowGrantPermission`.
The `ClaimModifiedEvent` (which is now cancellable thanks to TechFortress/GriefPrevention#942, contrary to the comment from the original implementation... whoops) can be used to replace `IAddonPlugin#mayResizeClaim`.
The only thing there is not a full replacement for is `IAddonPlugin#mayAbandonClaim` - unfortunately, the `ClaimDeleteEvent` is not cancellable. However, you could easily hack around this by forcibly recreating the claim whenever it is abandoned and warning the user.

**Comment by EtienneDx** [comment]
Hey Jikoo, thanks a lot for pointing this out, I haven't had the time to check the GP repo lately, that's a great change! Idk when I'll have time to change this but now that I know it exists, I will, no doubt about it :)
Hopefully it won't take too long to change it and will save me quite some time in the future once implemented. This split version was really bugging me out too but I had no better option at the time, and no time since ^^

**Comment by LcorpOfficial** [comment]
> I'm afraid they're aren't compatible... I might re-update the modified version, but I'm kinda busy rn... For the best, I'll need GP to finish working on it's latest version but I think that's still way off, sorry :/

Just a heads up, I know you're a busy one: GP has a new RC and with 1.18.1 having a stable release I think you can reach all your goals with compat via API and future-proofing the plugin for fewer release interval needs.


https://github.com/TechFortress/GriefPrevention/discussions/1714

**Comment by EtienneDx** [comment]
Hey, thanks for the news, I've started to integrate it, I hope to get a funcitonning version soon. As you know I'm relatively busy, but I'll try to get a functionning version out soon. I'll also have a look at other problems that have been reported if I have the time (renewrent).
Btw, I'm moving as much of the messages into config files as I can so that translations and customizations become doable soon. Hopefully I can get all of this to work soon, I'll keep you posted :)

**Comment by joex92** [comment]
I hope the next release would work on 1.17 and 1.18...

**Comment by EtienneDx** [comment]
I have been testing the 1.4.0 pre-release today using 1.17, it seems to be working fine. I'll release this preview version tonight so that you might help me out testing it (and hopefully translating it). Hopefully we can get a fully tested version in the next 5-10 days.
I can also confirm that from 1.4.0 on, RealEstate will be relying on the original GreifPrevention plugin!

**Comment by LcorpOfficial** [comment]
Sweet! that's wonderful. I'll get right to work testing it when I get a sec.

**Comment by EtienneDx** [comment]
I'm glad to announce that RealEstate will now depend on the native GriefPrevention plugin v16.18, which means I can finally close this issue!
