### ISSUE TITLE
Server admins cannot abandon rented (sub)claim

### ISSUE THREAD

**Issue by DmitryRendov** [EtienneDx/RealEstate#19]
Being the server operator and having an admin claim for rent there's no way
* to perform /trustlist to check the permissions
* to run /abandonclaim to remove this claim
* even using /abandonallclaims or /abandontopclaim to remove parent and all sub claims -- looks like rented claims are still in database.

Any hints, how server admins can clean up user's or admin's claims rented by players?
And sorry if that is not an issue but expected behavior.

**Comment by EtienneDx** [comment]
Not sure wether it's an issue or expected ^^
I'm stopping claim owners from modifying or abandonning rented claim since someone's supposed to be using it...
I guess it makes sense that admins can perform those commands, I'll mark that as a bug (it's also a good way to get deeper in the code if you want to try and fix it ^^)

**Comment by EtienneDx** [comment]
Alright, now we provide a way for admin to take part into the exit offers. It doesn't allow admin to abandon rented claims, but I don't think it should.
I'll add another issue to add a command allowing admins to cancel transactions
